name: base
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch>=2.4.0,<3.0.0
    - transformers>=4.46.0,<6.0.0
    - safetensors>=0.4.3,<1.0.0
    - fast_hadamard_transform>=1.0.0,<2.0.0
    - tilelang==0.1.6
